### ISSUE TITLE
Provider registry.terraform.io/ugns/bref v0.3.3 does not have a package available for your current platform, linux_amd64.

### ISSUE THREAD

**Issue by conradkirschner** [UGNS/terraform-provider-bref#89]
Hi there,

Could it be that there is no provider for linux_amd64?

**Comment by jbouse** [comment]
Yeah there's an issue with the @hashicorp registry as the organization name changed from `UGNS` to `ugns` and their system is broken in handling this. I've been opening tickets with @hashicorp to fix it but because I don't pay them money they close them without taking any actions.

**Comment by conradkirschner** [comment]
mh, so this will not fixed until hashicorp will fix it?
Then I going to compile the php lambda layer by my own? 

Or any recommendation?

**Comment by conradkirschner** [comment]
@jbouse  maybe you create a new organisation ugns_v2 or something else as workaround? 
(I will close this ticket cause it's a duplicate of #76)

**Comment by jbouse** [comment]
The problem is that the @hashicorp registry is case-insensitive on some things and case-sensitive on others... From the web UI you can find using either case but when it comes to providers they only look for the GPG signing key in a case-sensitive manner which is where the issue is coming from. They (@hashicorp) have no way to remove and re-add a provider or module and unless you're a partner or a paying customer they don't appear to care about helping correct issues as my tickets keep getting closed with no action.

**Comment by conradkirschner** [comment]
So create a "new" organisation e.g. "ugns_bref" as workaround should work? 

Another idea for me now is to not load it from the registry - but this might lead in no update for the future. 
(in combination with the new generated layers maybe not a cool solution)

**Comment by jbouse** [comment]
To change the organization, I have to change or create an entirely new GitHub account and move the repo.

**Comment by conradkirschner** [comment]
if it only affects the bref terraform provider - a mirror repo might be a workaround... 
https://github.com/marketplace/actions/mirroring-repository


I don't like the idea, but it is what it is if hashicorp doesnt offer any help.
